{% set name = "nengo-extras" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nengo-extras-{{ version }}.tar.gz
  sha256: 234f41d777a6f5085378ed4f8145326b735b3ba34f8a392f7357ed6547414fa6

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - numpy
    - pip
    - python {{ python_min }}
  run:
    - matplotlib-base
    - nengo
    - numpy
    - python >={{ python_min }}
    - pillow
    - pyopencl
    - mako
    - nengo-ocl

test:
  imports:
    - nengo_extras
    - nengo_extras.networks
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/nengo/nengo-extras
  summary: Lesser used features for the Nengo neural simulator
  license: LicenseRef-NENGO
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - Tobias-Fischer
